#!/usr/bin/env python3
"""Send a test email through AWS SES with the Sessy Configuration Set."""

import argparse
import sys
from pathlib import Path

# Add backend directory to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.config.settings import settings
from app.modules.email.service import email_service


def main():
    parser = argparse.ArgumentParser(
        description="Send a test email through AWS SES v2 using the Sessy Configuration Set."
    )
    parser.add_argument(
        "to_email",
        help="Destination email address (e.g. you@example.com)",
    )
    parser.add_argument(
        "--from-email",
        default=None,
        help="Sender email address (default: SES_FROM_EMAIL or noreply@kova.app)",
    )
    parser.add_argument(
        "--config-set",
        default=None,
        help="Configuration Set name (default: SES_CONFIGURATION_SET or 'production-ses')",
    )
    parser.add_argument(
        "--subject",
        default="Sessy SES Verification Test Email",
        help="Email subject line",
    )

    args = parser.parse_args()

    config_set = args.config_set or settings.SES_CONFIGURATION_SET or "production-ses"
    sender = args.from_email or settings.SES_FROM_EMAIL or "noreply@kova.app"

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family: sans-serif; line-height: 1.5; color: #111;">
      <h2>Sessy Test Email</h2>
      <p>This is a verification test email sent through AWS SES using configuration set <strong>{config_set}</strong>.</p>
      <p>Recipient: {args.to_email}</p>
      <p>Sender: {sender}</p>
      <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
      <p style="font-size: 12px; color: #666;">Generated by Kova Email Service for Sessy activation.</p>
    </body>
    </html>
    """

    print(f"Sending test email to: {args.to_email}")
    print(f"From: {sender}")
    print(f"Configuration Set: {config_set}")
    print(f"Region: {settings.AWS_REGION}")
    print(f"Configured: {email_service.is_configured}")

    success = email_service.send_email(
        to_email=args.to_email,
        subject=args.subject,
        html_body=html_content,
        from_email=sender,
        configuration_set=config_set,
    )

    if success:
        print("\nTest email successfully sent/dispatched!")
        sys.exit(0)
    else:
        print("\nFailed to send test email. Check your AWS credentials and SES identity permissions.")
        sys.exit(1)


if __name__ == "__main__":
    main()
